 <ol class="breadcrumb">
  <li><a href="<?php echo $this->basePath()?>/">Inicio</a></li>
  <li class='active'>Iniciar Sesión</li>
</ol>
<style type="text/css">
.login {
overflow: hidden;
}
.clientes {
margin-left: auto;
margin-right: auto;
padding: 20px;
background-color: #F5F7F5;
border: 3px solid #EAECF3;
-moz-border-radius: 7px;
-webkit-border-radius: 7px;
}
</style>
<div class='login'>

<div class="clientes col-md-4">
<?php 
$form=$this->form;
$form->setAttribute('action', $this->basePath().'/usuario/');
$formLabel = $this->plugin('formLabel');

// Render the opening tag
echo $this->form()->openTag($form);
?>

 <h2 class="form-signin-heading"><?php echo $this->titulo?></h2>
<div class="form-group">
<?php 

$usuario = $form->get('username');
$usuario->setAttribute('value', $this->usuario);
echo $this->formElementErrors($usuario);
echo $formLabel->closeTag();
echo $this->formInput($usuario);
?>
</div>
<div class="form-group">

<?php 
$password = $form->get('password');
$password->setAttribute('value', $this->password);
echo $this->formElementErrors($password);
echo $formLabel->closeTag();
echo $this->formInput($password);
?>

</div>
<div class="form-group">
<div><?php echo $this->mensaje; ?></div>
<?php 
$send = $form->get('send');
echo $this->formElement($send);
echo $formLabel->closeTag();
?>
<hr>
<a href=""><img src=""><img style='height:40px;' src="<?php echo $this->basePath()?>/img/facebook-login.png"></a><br>
<a href="">Olvidé mi contraseña</a> 
</div>


</div>

</div>
