<div class='menu'>
<ol class="breadcrumb"> <li><a href="#">HOME</a></li><li><a href='<?php echo $this->basePath().'/usuario';?>'>Usuario</a></li> <li>Cpanel</li> <li ><?php echo $this->nombre_usuario?></li><li><a href='<?php echo $this->basePath().'/usuario/usuario/logout';?>' class="btn-sm btn-warning">SALIR</a></li> </ol>
</div>
<style>
ul {
width: 30%;
	margin-right: 1%;
float: left;
overflow: hidden;
/* background-color: #F3F5F3; */
border: rgb(235, 235, 235);
border-style: solid;
-webkit-border-radius: 5px;
-moz-border-radius: 5px;
border-radius: 15px;
padding: 10px;
}
h2 {
text-align: center;
	font-size:18px;
	margin-bottom: 20px
}
li.punt {
display: block;
font-family: myriad-it;
font-size: 14px;
background-image: url(../../img/palomita.png);
background-repeat: no-repeat;
padding-left: 38px;
padding-bottom: 7px;
}
</style>
<div class='left'>
</div>
<div class='rigth'>
<ul>
<h2>Paquete Básico </h2>
<li class='punt'>Micrositio <strong>(Ejemplo: www.empresasveracruz.com.mx/TUEMPRESA)</strong></li>
<li class='punt'>Optimización SEO a tu anuncio</li>
</ul>
<ul>
<h2>Paquete Estandar </h2>
<li class='punt'>Micrositio <strong>(Ejemplo: www.empresasveracruz.com.mx/TUEMPRESA)</strong></li>
<li class='punt'>Optimización SEO a tu anuncio</li>
<li class='punt'>5 Imágenes Disponibles (De su empresa)</li>
<li class='punt'>Banner 260px Disponible <span>Visible en los sitios de su categoría</span></li>
<li class='punt'>1 Video enlazado de Youtube</li>
<li class='punt'>Ubicación en Google Maps</li>
</ul>
<ul>
<h2>Paquete Premium </h2>
<li class='punt'>Micrositio <strong>(Ejemplo: www.empresasveracruz.com.mx/TUEMPRESA)</strong></li>
<li class='punt'>5 Imágenes Disponibles (De su empresa)</li>
<li class='punt'>Banner 260px Disponible <span>Visible en los sitios de su categoría</span></li>
<li class='punt'>Ubicación en Google Maps</li>
<li class='punt'>1 Video enlazado de youtube</li>
<li class='punt'>1 Campaña en Google Adwords Gratis con valor de $1,200.00</li>
<li class='punt'>Diseño de Página web con Dominio y Hosting (5 Pestañas)</li>
<li class='punt'>Optimización SEO a anuncio y web</li>
<li class='punt'>2 envíos de Mailing a 3,000 clientes potenciales del Estado de Veracruz.</li>
</ul>
</div>
