<?php 
use Principal\Model\Entity\Busqueda;
?>
<link rel="stylesheet" href="/css/jquery-ui.css">
  <script src="/js/jquery-ui.js"></script>
<div class="header">
		<h1 class="hide-text">Directorio de Empresas</h1>
			<div class="sup">
			
					<div class="logo"></div>
					
					<div class="search">
            <div class='simple'></div>
            <div class='buscador'>
					<?php 
$form = $this->form;
$form ->prepare();
$form->setAttribute('action', $this->basePath().'veracruz/a/index_redirect');
$formLabel = $this->plugin('formLabel');
// Render the opening tag
echo $this->form()->openTag($form);
$search = $form->get('search');
echo $this->formInput($search);
echo $this->formElementErrors($search);
echo $formLabel->closeTag();
$ciudad = $form->get('ciudad2')->setEmptyOption('Seleccione la ciudad...');
$ciudad->setValueOptions($this->municipios);
echo $this->formSelect($ciudad);
echo $this->formElementErrors($ciudad);
echo $formLabel->closeTag();
?>
<input type="submit" value="" class="imgClass" />
<?php
echo $this->form()->closeTag($form);


?>
</div>
</div></div>
			</div>
			
				<div class="menu"> <ul>
							<li class="menul"><a href="http://www.empresasveracruz.com.mx">Inicio</a></li>
							<li class="menul"><a href="http://www.empresasveracruz.com.mx/soluciones_pymes">Soluciones <span>PYMES</span></a></li>
							<li class="menul"><a href="">Tu empresa <span>GRATIS</span></a></li>
							<li class="menul"><a href="http://www.empresasveracruz.com.mx/acceso_clientes">Clientes</a></li>
							
					</ul></div>
		
      <div class="container">
      	<div class="contenido">
      	<div class="addpyme">
      			<div><a class='active' style="cursor:pointer">Cupones <span>Gratuitos</span></a>
      			
      				<div class='muestra'>
      				<h3>!Recibe Cupones de Descuento COMPLETAMENTE <span> GRATIS</span>!</h3>
      				<?php $formreg = $this->formRegistro;
      						$formreg->prepare();
      						$formreg->setAttribute('action', 'registro_nuevo.usuario');
      					
      						$formLabel = $this->plugin('formLabel');
      						// Render the opening tag
      						echo $this->form()->openTag($formreg); 
      						?>
      						<br><label>Correo Electr&oacutenico:</label><br>
      						<?php 
      						$email = $formreg->get('email');
      						echo $this->formInput($email);
      						echo $this->formElementErrors($email);
      						echo $formLabel->closeTag();
      						
      						?>
							<br><label>Contrase&ntildea:</label><br>
      						<?php 
      						$password = $formreg->get('password');
      						echo $this->formInput($password);
      						echo $this->formElementErrors($password);
      						echo $formLabel->closeTag();
      						
      						?>
      						<br><label>Repite Contrase&ntildea:</label><br>
      						<?php 
      						$password2 = $formreg->get('repeatPassword');
      						echo $this->formInput($password2);
      						echo $this->formElementErrors($password2);
      						echo $formLabel->closeTag();
 
      						
			      				?>
      							<hr />
                    <a class="btn btn-sm btn-primary btn-block" onclick="registrar();">Recibir Descuentos</a>
      					  <?php 
      					   
      					   echo $this->form()->closeTag($formreg); ?>
      					  
      				</div>
      			
      			</div>
      	</div>
      	<div class="slideshow">
      	<style type="text/css">
        #dialog-message{
          display: none;
        }

          </style>
      		<div id="dialog-message" title="¡Alerta!">
</div>

    <div id="galery"><script type="text/javascript">
			
				jQuery(document).ready(function($) {
					
					$("#DDSlider").DDSlider({
						
						trans: "random",
						delay: 50,
						waitTime: 5000,
						duration: 500,
						stopSlide: 1,
						bars: 15,
						columns: 10,
						rows: 3,
						ease: "swing",
						selector: "#DDSelectors",
						nextSlide: "#DDNextSlide",
						prevSlide: "#DDPrevSlide"
						
					});
					
				});
				
			</script>
			
			<style type="text/css">
			
				#DDSlider, #DDSlider li {
					
					width: 684px;
					height: 277px;
					
				}
			
			</style>
			<style type="text/css">
		  
			  #DDPrevSlide {
				  
				  width: 22px;
				  height: 22px;
				  background: url() no-repeat center center;
				  position: absolute;
				  z-index: 15;
				  cursor: pointer;bottom: 10px; left: 10px;}#DDNextSlide {
				  
				  width: 22px;
				  height: 22px;
				  background: url(../img/arrowRight.png) no-repeat center center;
				  position: absolute;
				  z-index: 15;
				  cursor: pointer;bottom: 10px; left: 37px;}</style><style type="text/css">#DDSelectors {
							
								position: absolute;
								list-style: none;
								z-index: 15;
								padding: 0;
								margin: 0;bottom: 10px; right: 10px;
							
								}
								
								#DDSelectors li {
									
									float: left;
									margin: 0 3px;
									padding: 0;
									cursor: pointer;
									height: 10px;
									width: 10px;
									background: url() no-repeat center center;
									
								}
								
								#DDSelectors li.current {
									
									float: left;
									margin: 0 3px;
									cursor: pointer;
									height: 10px;
									width: 10px;
									background: url() no-repeat center center;
									
								}
								
								</style><div id="DDSliderCont" style="position: relative; float: left;"><ul id="DDSlider">
								<li style="background: #fff;" title="barBottom">
								<a href="http://www.bio-aqua.mx" title='Agua Purificada'><img src="<?php echo $this->basePath() .'/img/slideshow/bioaqua.jpg'?>" alt="" /></a></li>
								<li style="background: #fff;" title="barFadeRandom">
								<img src="<?php echo $this->basePath() .'/img/slideshow/cupones.jpg'?>" alt="" /></li>
								</ul>
								<div id="DDNextSlide"></div><div id="DDPrevSlide"></div><ul id="DDSelectors"></ul></div></div>
        
      	
      	
      	
      	</div>

      	<br>
		<div class="nueva">Descuentos <span>Cupones </span></div>


      <!-- Nº of items per page form -->
      
      <br />
      <div class="paginador">
      <form>
        <label>Empresas por p&aacutegina: </label>
        <select class="select">
          <option>9</option>
          <option>12</option>
          <option>18</option>
        </select>
      </form>


      <!-- item container -->
    <ul id="itemContainer">
      
          <?php $total_rating=0; $suma_value_rating=0; $contador=0;
          foreach ($this->empresas as $empresa){
                if ($empresa['num_rating']<>null && $empresa['num_rating']<>0){
                $contador = $contador + 1;
                $total_rating = $total_rating+$empresa['num_rating'];
                $suma_value_rating= $suma_value_rating+$empresa['suma_ratings'];
                }
               @$value_emp=number_format(($empresa['suma_ratings']/$empresa['num_rating']),1);
            ?>

              <li class="pyme-list">
                <div>

                <span itemscope itemtype="http://schema.org/LocalBusiness">

                <?php if ($value_emp==null || $value_emp == 0.00) { ?>
                <img src="http://www.empresasveracruz.com.mx/img/0_star.png" style="width:100px; height:20px; margin:-3px;" /> 
                <?php  } 
                elseif ($value_emp >= 9.6) { ?>
                <img src="http://www.empresasveracruz.com.mx/img/5_star.png" style="width:100px; height:20px; margin:-3px;" /> 
                <?php  } 
                elseif ($value_emp >= 8.3) { ?>
                <img src="http://www.empresasveracruz.com.mx/img/4_5_star.png" style="width:100px; height:20px; margin:-3px;" /> 
                <?php  } 
                elseif ($value_emp >= 7.6) { ?>
                <img src="http://www.empresasveracruz.com.mx/img/4_star.png" style="width:100px; height:20px; margin:-3px;" /> 
                  <?php  } 
                elseif ($value_emp >= 6.5) { ?>
                <img src="http://www.empresasveracruz.com.mx/img/3_5_star.png" style="width:100px; height:20px; margin:-3px;" /> 
                  <?php  } 
                elseif ($value_emp >= 5.5) { ?>
                <img src="http://www.empresasveracruz.com.mx/img/3_star.png" style="width:100px; height:20px; margin:-3px;" /> 
                  <?php  } 
                elseif ($value_emp >= 4.5) { ?>
                <img src="http://www.empresasveracruz.com.mx/img/2_5_star.png" style="width:100px; height:20px; margin:-3px;" /> 
                  <?php  } 
                elseif ($value_emp >= 3.5) { ?>
                <img src="http://www.empresasveracruz.com.mx/img/2_star.png" style="width:100px; height:20px; margin:-3px;" /> 
                  <?php  } 
                elseif ($value_emp >= 2.5) { ?>
                <img src="http://www.empresasveracruz.com.mx/img/1_5_star.png" style="width:100px; height:20px; margin:-3px;" /> 
                  <?php  } 
                else { ?>
                <img src="http://www.empresasveracruz.com.mx/img/1_star.png" style="width:100px; height:20px; margin:-3px;" /> 
                <?php  }?>
              


                <br>
        <a href='http://www.empresasveracruz.com.mx/<?php echo $empresa['url']?>' title="<?php echo $empresa['nombre_categoria']?> <?php echo $empresa['Ciudad']?>"><h2 itemprop="name"><?php echo $empresa['Nombre']?></h2></a>
        <h5><?php echo $empresa['nombre_categoria']?> en <?php echo $empresa['Ciudad']?></h5>
        <span itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">

        <p> <span itemprop="streetAddress"><?php  echo $empresa['Direccion']." #".$empresa['Numero']?></span><span itemprop="addressLocality"> <?php  echo $empresa["Colonia"]?></span>,
          <span itemprop="addressRegion"> <?php  echo " ".$empresa["Ciudad"]?></span>, Veracruz
          <span itemprop="postalCode"><?php echo $empresa['Codigo_postal']." "?></span>
        </span>
          </p>
          </span>
        </div>
      </li>
            <?php
            }
          

            
          ?>
         </ul>
         
         
      <!-- navigation holder -->
      <div class="holder"></div>
       <div class='informacion'>

            <div><h4>¿Porqué anunciarse en <span>empresasveracruz.com.mx</span>?</h4>
                <p>Mejores Precios Garantizados, Posicionamiento SEO, Visitas Reales, Micrositio propio, Disponibilidad 24/365, Pagos Mensuales, Galería de Imágenes, Videos, Email Marketing, Posicionamiento Orgánico, Promocionar cupones de productos y/o servicios.</p>
            </div>
            <div><h4>¿Porqué visitar <span>empresasveracruz.com.mx</span>?</h4>
              <p>Cupones gratuitos, nuevas ofertas, recomendaciones y opiniones de miles de usuarios reales</p>
            </div>

            <ul><h4>Clientes <span>Recientes</span></h4>
              <?php foreach ($this->logos as $logo) {?>
                <img src='../img/logos/<?php echo $logo['nombre_foto'] ?>' alt="<?php echo $logo['nombre']?>" style='width: 50px; height: 30px; border: 1px;' />
                <?php
              }?></ul>   


              <ul><h4 class='videos'>Videos<span> Promocionales</span></h4>
               
              </ul>

          </div>
			</div>
		<div class="slider-derecho">
          <div class="rating" itemscope itemtype="http://data-vocabulary.org/Review-aggregate">
          			<?php $valor = @number_format(($suma_value_rating/$total_rating),1);?>
    				<span class='punts' itemprop="average"><?php echo $valor ?></span> <p>de <strong itemprop="best">10</strong> Puntos</span><br>
                <span itemprop="rating" itemscope itemtype="http://data-vocabulary.org/Rating">
                    <span>Basado en 
                            <strong itemprop="count"><?php echo $total_rating ?></strong> Opiniones
                      </span>
                                                
                </span>
                ¡Comprobamos todos los comentarios!.
                </p>
          </div>

          			<div class="premium"> </div>

     			<div class="cupones"><h4><span>Cupones</span> Descuentos</h4>
     			<?php foreach ($this->cupones as $cupon){

     				?>
     				<div class='cupon'>

              <?php if ($cupon['tipo']=='D'){ ?> 
              <h5><?php echo "<strong>".number_format($cupon['porcentaje'],0)."%</strong>"."<span> Descuento</span>"; ?></h5><?php echo $cupon['Detalles']?>
              <p><strong>De: <span>$<?php echo number_format($cupon['valor_real'],2)?></span> a sólo <span>$<?php echo number_format($cupon['valor_desc'],2)?></span></strong></p>
              <a class="fancybox fancybox.iframe" href="comisionista/">Obtener Cupón</a>
              <?php 
            }
                else { ?>

                    <h5><?php echo "<strong>Oferta</strong><span> Especial</span>"; ?></h5><?php echo $cupon['Detalles']?>
              <p><strong>Por sólo: <span>$<?php echo number_format($cupon['valor_real'],2)?></span></strong></p>
              <a class="fancybox fancybox.iframe" href="comisionista/">Obtener Oferta</a>

                <?php 
                }
              ?>
            </div>
     				<?php 
     				
     			}?>
     			
     			
     			
     			</div>
     			
     			
     			
     		</div>
		<div class="categorias"><h1 class='nueva'>GIROS <span>COMERCIALES</span></h1>
		<ul class='categorias-ul'>
		<?php $Busqueda= new Busqueda();?>
			<?php
			
			 foreach ($this->categorias as $categoria){
			 	$nombre_categoria=$categoria['nombre_categoria'];
	            $url=$Busqueda->getUrl($categoria['nombre_categoria']);

				?>
				
				<li class="categoria-list"><a href="<?php echo $this->basePath() . '/'; echo $url;?>
					-en-Veracruz" title="<?php echo $categoria['nombre_categoria'].' en Veracruz'; ?>"><?php 
				echo $nombre_categoria;  ?></a></li>
				<?php 
				
			}?>
		
		</ul>
		
		
		</div>	
			
     		
	  </div>
			
    </div> <!--! end of #content -->
    
    <div class='footer'>

        <div class='sup-footer'>
          <div>
          <h3>Directorio de <span>Empresas</span> en:</h3>
          <?php foreach ($this->directorios as $directorio) {

            if ($directorio['nombre_m']=='Xalapa' || $directorio['nombre_m'] == 'Coatzacoalcos' || $directorio['nombre_m'] == 'Actopan' || $directorio['nombre_m'] == 'Xalapa' || $directorio['nombre_m'] == 'Boca del Río' || $directorio['nombre_m'] == 'Alvarado' || $directorio['nombre_m'] == 'Coatepec' || $directorio['nombre_m'] == 'Banderilla' || $directorio['nombre_m'] == 'Veracruz'){
              echo "<a href='http://www.empresasveracruz.com.mx/en-".$directorio['url_m']."-Veracruz' title='Empresas en ".$directorio['nombre_m']."'><strong>".$directorio['nombre_m'].'</strong>, '."</a>";
            }
            else{
          	echo "<a href='http://www.empresasveracruz.com.mx/en-".$directorio['url_m']."-Veracruz' title='Empresas en ".$directorio['nombre_m']."'>".$directorio['nombre_m']."</a>, ";
          }
          }?>
        </div>
         <div class="icon-social"><h3>Redes <span>Sociales</span></h3>
          <a class='facebook' href="https://www.facebook.com/empresasver"></a>
          <a class='twitter' href="https://www.twitter/empresasver"></a>
          <a class='google' href=""></a>
          <p>Directorio Empresas Veracruz<br>Av. Rebsamen #465 Int-9, Mártires de Chicago, Xalapa, Veracruz | México <br> info@empresasveracruz.com.mx (279)112.21.28</p>
         </div>

        </div>
        <div class='privacidad'><a href="">Politicas de Privacidad</a>
          <a class='diseno_web' href="http://www.arcesystems.com.mx" title="Diseño Web Xalapa"></a>
        </div>
        <div class='inf-footer'>
          <div>
        <a class='contacto' href=""></a><a class='rss' href=""></a><p>Copyright © 1996–2014 empresasveracruz.com.mx ™. Todos los derechos reservados</p>
        </div>
        </div>

      </div>
    <!-- AddThis Smart Layers BEGIN -->
<!-- Go to http://www.addthis.com/get/smart-layers to customize -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-531b80c84837d17f"></script>
<script type="text/javascript">
  addthis.layers({
    'theme' : 'transparent',
    'share' : {
      'position' : 'left',
      'numPreferredServices' : 5
    }, 
    'follow' : {
      'services' : [
        {'service': 'facebook', 'id': 'empresasver'},
        {'service': 'twitter', 'id': 'empresasver'},
        {'service': 'linkedin', 'id': 'empresasveracruz'},
        {'service': 'google_follow', 'id': '106762300804885537042'}
      ]
    },  
    'whatsnext' : {},  
    'recommended' : {} 
  });
</script>
<!--Start of Zopim Live Chat Script-->
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute('charset','utf-8');
$.src='//cdn.zopim.com/?1xMilBxhXrI365ibB4Z6GxPj1SzoVMT6';z.t=+new Date;$.
type='text/javascript';e.parentNode.insertBefore($,e)})(document,'script');
</script>
<!--End of Zopim Live Chat Script-->
    
			
		
		