<link rel="stylesheet" href="/css/jquery-ui.css">
  <script src="/js/jquery-ui.js"></script>
<div class="header">
		<h1 class="hide-text">Directorio de Empresas</h1>
			<div class="sup">
					<div class="logo"></div>
				</div>
</div>
	<div class="menu"> <ul>
							<li class="activado"><a href="http://www.empresasveracruz.com.mx">Pymes</a></li>
							<li class="menul"><a href="http://www.empresasveracruz.com.mx/soluciones_pymes" title='Soluciones de Marketing Para PYMES'>Soluciones <span>PYMES</span></a></li>
							<li class="menul"><a href="http://www.empresasveracruz.com.mx/descuentos_cupones">Cupones</a></li>
							<li class="menul"><a href="">Tu empresa <span>GRATIS</span></a></li>
							<li class="menul"><a href="http://www.empresasveracruz.com.mx/acceso_clientes">Clientes</a></li>
							
					</ul></div>
			