   <link href="../css/kendo.common.min.css" rel="stylesheet" />
    <link href="../css/kendo.default.min.css" rel="stylesheet" />


<script type="text/javascript">
document.getElementById('nombre').disabled = true;
document.getElementById('email').disabled = true;
</script>
<div id="example" class="k-content">
    <div>
        <?php if ($this->username==null){?>
        <div class='mensaje'>
            <form action='send_msj' method='POST'>
        <ul class="forms">
            <li>
                <label>Nombre: </label><input name='nombre' type="text" class="k-textbox" value="<?php echo $this->nombre?>" readonly="true" />
                <label>Correo Electrónico:</label><input type="text" name='email' class="k-textbox" value="<?php echo $this->email_user?>"  readonly="true" />
                <label>Asunto:</label><input type="text" name='asunto' class="k-textbox" value="" placeholder='Asunto' />
                <input type="hidden" name='id_empresa' class="k-textbox" value="<?php echo $this->id_empresa?>" />
                <input type="hidden" name='id_user' class="k-textbox" value="<?php echo $this->id_user?>" />
               
            </li>
            <li><label>Mensaje:</label><textarea class="k-textbox" value="" name='mensaje' placeholder='Escribe tu mensaje aqui.'></textarea></li><br>
             <button class="k-button" type='submit'>Enviar Mensaje</button>
        </ul>
        </form>
    </div>
       <?php }?>
        
        <style scoped>

            .mensaje {
                width: 600px;
            }
            .forms {
            	width: 500px;
            	margin-top: 30px;
                float: left;
                color: #2a3062;
            }

            .forms li {
                margin-bottom: 5px;
                list-style: none;
            }

            .forms li > * {
                width: 300px;
            }
        </style>
    </div>
</div>
<style type="text/css">footer{
    display: none;
    }</style>