   <link href="../css/kendo.common.min.css" rel="stylesheet" />
    <link href="../css/kendo.default.min.css" rel="stylesheet" />
    <!-- Just for syntax highlighting: -->
        <link href="<?php echo $this->basePath().'/css/'?>prettify.css" rel="stylesheet" type="text/css">
        
        <!-- jQuery 1.3: -->
        <script src="<?php echo $this->basePath().'/js'?>/jquery-1.8.2.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath().'/js'?>/bsa.js" type="text/javascript"></script>
        <style>
#imgPreviewWithStyles {
    background: #222;
    -moz-border-radius: 10px;
    -webkit-border-radius: 10px;
    padding: 15px;
    z-index: 999;
    border: none;
}

/* Text below image */
#imgPreviewWithStyles span {
    color: white;
    text-align: center;
    display: block;
    padding: 10px 0 3px 0;
}   </style>
        <script type="text/javascript">
(function(){
  var bsa = document.createElement('script');
     bsa.type = 'text/javascript';
     bsa.async = true;
     bsa.src = '//s3.buysellads.com/ac/bsa.js';
  (document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0]).appendChild(bsa);
})();
</script>
        <ul id="fifth">
        <li><a href="http://google.com/" rel="http://www.e/img/banner/B260/joao.png">Google</a></li>
        <li><a href="http://yahoo.com/" rel="http://www.e/img/banner/B260/joao.png">Yahoo</a></li>
        <li><a href="http://amazon.com/" rel="http://www.e/img/banner/B260/joao.png">Amazon</a></li>
    </ul>
     
    <script type="text/javascript">
    //<![CDATA[
jQuery.noConflict();
$(document).ready(function(){
$("#fifth a").imgPreview({
    containerID: 'imgPreviewWithStyles3',
    srcAttr: 'rel',
    imgCSS: {
        // Limit preview size:
        height: 200
    },
    // When container is shown:
    onShow: function(link){
        $('<span>' + link.href + '</span>').appendTo(this);
    },
    // When container hides: 
    onHide: function(link){
        $('span', this).remove();
    }
});


})(jQuery);
    //]]></script>
    <script src="<?php echo $this->basePath().'/js'?>/imgpreview.full.jquery.js" type="text/javascript"></script>
    <script src="<?php echo $this->basePath().'/js'?>/prettify.js" type="text/javascript"></script>
    
<script type="text/javascript">
document.getElementById('nombre').disabled = true;
document.getElementById('email').disabled = true;
</script>
<div id="example" class="k-content">
    <div>
        <?php if ($this->username==null){?>
        <div class='mensaje'>
            <form action='send_msj' method='POST'>
        <ul class="forms">
            <li>
                <label>Nombre: </label><input name='nombre' type="text" class="k-textbox" value="<?php echo $this->nombre?>" readonly="true" />
                <label>Correo Electrónico:</label><input type="text" name='email' class="k-textbox" value="<?php echo $this->email_user?>"  readonly="true" />
                <label>Asunto:</label><input type="text" name='asunto' class="k-textbox" value="" placeholder='Asunto' />
                <input type="hidden" name='id_empresa' class="k-textbox" value="<?php echo $this->id_empresa?>" />
                <input type="hidden" name='id_user' class="k-textbox" value="<?php echo $this->id_user?>" />
               
            </li>
            <li><label>Mensaje:</label><textarea class="k-textbox" value="" name='mensaje' placeholder='Escribe tu mensaje aqui.'></textarea></li><br>
             <button class="k-button" type='submit'>Enviar Mensaje</button>
        </ul>
        </form>
    </div>
       <?php }?>
        
        <style scoped>

            .mensaje {
                width: 600px;
            }
            .forms {
            	width: 500px;
            	margin-top: 30px;
                float: left;
                color: #2a3062;
            }

            .forms li {
                margin-bottom: 5px;
                list-style: none;
            }

            .forms li > * {
                width: 300px;
            }
        </style>
    </div>
</div>
<style type="text/css">footer{
    display: none;
    }</style>