<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="/img/favicon.ico">

    <title>Juicios Orales | Cursos</title>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.css" rel="stylesheet">
    <link href="css/index.css" rel="stylesheet">
  </head>
<body>
        <header><a href=""><div class='header'><img src="../img/juicios-orales.png"></a>
            </div>

        </header>
        <div class='line'>
                <div class='menu'><ul class='one'><li>|<a href="">PRINCIPAL</a>|</li><li>|<a href="">INFORMES</a>|</li><li>|<a href="">PROGRAMA</a>|</li></ul></div>
            </div>
        <div class="container">
       
            <?php echo $this->content; ?> 

            
        </div> <!-- /container -->
        <footer>
            <div class='linea'></div>
                <div class='pie'>
                    <ul>
Juicios Orales<br>
Cursos de Juicios Orales<br>
Capacitación Juicios Orales<br>
Correcta aplicación del juicio oral<br>

</ul>
                    <ul></ul>
                    <ul>Prolongacion rebsamen #645 int. 9 Col. martirez de chigago, Xalapa, Ver.<br>
                    contacto@juicios-orales.com<br>
                    01 (228)8.17.42.67</ul>
                    
                </div>
                <p>Todos los derechos reservados copyright 2013 © Ocampo y Asociados
Desarrollado por: EmpresasVeracruz</p>
            </footer>
            <!--Start of Zopim Live Chat Script-->
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute('charset','utf-8');
$.src='//v2.zopim.com/?1xFRTGXv8P7A4ugDiMRvsVxsWHUZyZ8r';z.t=+new Date;$.
type='text/javascript';e.parentNode.insertBefore($,e)})(document,'script');
</script>
<!--End of Zopim Live Chat Script-->
    </body>
</html>