<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->titulo)->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath()?>/img/empresasveracruz2.png"></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <style type="text/css">
    ol {
        margin-top: 2.5%;
    }
    .navbar-inverse {
border-color: #47B11E;
border-bottom-width: 8px;
}
  .breadcrumb {
    padding: 5px 8px;
background-color: #47B11E;
}
ol>li>a{
    color: #fff;
}
.breadcrumb>.active {
color: #fff;
}
        #dialog-message{
          display: none;
        }
        img {
           height: 90px;
        }
        h2.form-signin-heading {
color: #F55B05;
font-size: 24px;
}


          </style>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p><small>EmpresasVeracruz.com.MX | El directorio empresarial más actual y eficiente del Estado de Veracruz.</small></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
