<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Soluciones Pymes');?>
        <?php echo $this->headMeta()->appendName('keywords', 'soluciones pymes, publicidad, marketing')?>
          <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>
   	
        
   		
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <!-- Le styles -->

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))

		->prependStylesheet($this->basePath() . '/css/jPages.css')
		->prependStylesheet($this->basePath() . '/css/animate.css')
         ->prependStylesheet($this->basePath() . '/css/index.css')
         ->prependStylesheet($this->basePath() . '/css/pymes.css')
         ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
         

        ?>
  
  <script type="text/javascript" src="<?php echo $this->basePath()?>/js/jquery-1.8.2.min.js"></script>
  <script type="text/javascript" src="<?php echo $this->basePath()?>/js/highlight.pack.js"></script>
  <script type="text/javascript" src="<?php echo $this->basePath()?>/js/tabifier.js"></script>
  <script src="<?php echo $this->basePath()?>/js/jPages.js"></script>
  <script src="<?php echo $this->basePath()?>/js/jquery.fancybox.js?v=2.1.4"></script>
  <link rel="stylesheet" href="<?php echo $this->basePath()?>/css/jquery.fancybox.css?v=2.1.4" type="text/css" /> 
   <script type="text/javascript" src="<?php echo $this->basePath()?>/js/script.js"></script>
  
<script type='text/javascript' src='<?php echo $this->basePath()?>/js/jcycle.js?ver=2.4'></script>
<script type='text/javascript' src='<?php echo $this->basePath()?>/js/jquery.DDSlider.min.js?ver=3.5.1'></script>
<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/DDSlider.css" type="text/css" /> 
  

  <script type="text/javascript">
  
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-28718218-1']);
  _gaq.push(['_trackPageview']);

  (function() {
	$('.fancybox').fancybox();
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

  </script>

  <script type="text/javascript">
  $(function() {

    /* initiate plugin */
    $("div.holder").jPages({
      containerID : "itemContainer",
      perPage : 9
    });

    /* on select change */
    $(".select").change(function(){
      /* get new nº of items per page */
      var newPerPage = parseInt( $(this).val() );

      /* destroy jPages and initiate plugin again */
      $("div.holder").jPages("destroy").jPages({
        containerID   : "itemContainer",
        perPage       : newPerPage
      });
    });

  });
  </script>

  
	<style type="text/css">
		.fancybox-custom .fancybox-skin {
			box-shadow: 0 0 50px #222;
		}
	</style>
   	</head>
    
		<body>
		
		<?php echo $this->content; ?>
	
		</body>
		
		
    
</html>