<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="/img/favicon.ico">
    <link href="../css/kendo.common.min.css" rel="stylesheet" />
    <link href="../css/kendo.default.min.css" rel="stylesheet" />
    <script src="../js/jquery.min.js"></script>
    <script src="../js/kendo.all.min.js"></script>
    <script src="../js/updateuser.js"></script>



    <!-- Bootstrap core CSS -->
    <link href="http://www.empresasveracruz.com.mx/css/bootstrap.css" rel="stylesheet">
    <link href="../css/clientes.css" rel="stylesheet">
  </head>
<body>
        <div class="container">
        	<div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand"><img src="/img/logo2.jpg" style='width:400px; height: 129px;'></a>
        </div>
        <div class="navbar-collapse collapse">
        </div>
      </div>
            
            <?php echo $this->content; ?>

        </div> <!-- /container -->
        <footer>
                
       
        <div class='inf-footer'>
          <div>
        <a class='contacto' href=""></a><a class='rss' href=""></a><p>Copyright © 1996–2014 empresasveracruz.com.mx ™. Todos los derechos reservados</p>
        </div>
        </div>


        </footer>
        
    </body>

</html>
