<style type="text/css">
.registro{
width: 400px;
min-height: 100px;
overflow: hidden;
margin-left: auto;
margin-right: auto;
}
</style>
<div class='registro'>
<form action="usuario_nuevo.usuario" method="post" name="registro" id="registro">      						<br><label>Correo Electrónico:</label><br>
      						<input name="email" type="email" placeholder="Correo Electrónico" class="input" id="email" required="required" value="">							<br><label>Contraseña:</label><br>
      						<input name="password" type="password" placeholder="Contraseña" class="input" required="required" value="">      						<br><label>Repite Contraseña:</label><br>
      						<input name="repeatPassword" type="password" placeholder="Repite Contraseña" class="input" required="required" value="">      							<hr>
      					  <input name="send" type="submit" class="btn btn-sm btn-primary btn-block" value="REGISTRARME"></form>

      					  </div>